[platformio]
default_envs = production

[env:production]
platform = espressif32@6.7.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_LOOP_STACK_SIZE=16384
  -DBOAT_EXPERIMENT=31
lib_deps =
  adafruit/Adafruit BNO08x @ 1.2.5
  adafruit/Adafruit BusIO @ 1.17.4
  sparkfun/SparkFun VL53L5CX Arduino Library
