[platformio]
default_envs = production

[env:production]
platform = espressif32@6.7.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_speed = 115200
upload_flags =
  --no-stub
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCOMPETITION_HARDWARE_ENABLE=1
